# ADに登場するキャラは 001_aurora_dream で定義
# TODO: 各キャラの誕生日調べる
# TODO: 各キャラの初登場回調べる
mia:
  actor_name: mia
  name: 上葉みあ
  cast_name: 大久保瑠美
  created_date: 2012-04-07 # ep 01
  birthday: 8/8
reina:
  actor_name: reina
  name: 深山れいな
  cast_name: 高森奈津美
  created_date: 2012-04-07 # ep 01
  birthday: 10/30
karin:
  actor_name: karin
  name: 志々美かりん
  cast_name: 津田美波
  created_date: 2012-04-07 # ep 01
  birthday: 5/10
ayami:
  actor_name: ayami
  name: 大瑠璃あやみ
  cast_name: 佐倉綾音
  created_date: 2012-04-07 # ep 01
  birthday: 1/6
# PURETTY のローマ字表記は発音をハングルに起こした上でローマ字化するイメージで
hyein:
  actor_name: hyein
  name: ヘイン
  cast_name: 伊藤かな恵 #TVシリーズ準拠
  created_date: 2012-04-07 # ep 01
somin:
  actor_name: somin
  name: ソミン
  cast_name: 三宅麻理恵 #TVシリーズ準拠
  created_date: 2012-04-07 # ep 01
siyun:
  actor_name: siyun
  name: シユン
  cast_name: 金香里 #TVシリーズ準拠
  created_date: 2012-04-07 # ep 01
chaegyeong:
  actor_name: chaegyeong
  name: チェギョン
  cast_name: 明坂聡美 #TVシリーズ準拠
  created_date: 2012-04-07 # ep 01
jaeeun:
  actor_name: jaeeun
  name: ジェウン
  cast_name: 米澤円 #TVシリーズ準拠
  created_date: 2012-04-07 # ep 01
# TODO: ボーイズ
